In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [4]:
test_data = pd.read_excel(r"C:\Users\ONYINYE EKEOCHA\Data_Test.xlsx")
test_data

TITLE  RESTAURANT_ID  \
0     CASUAL DINING           4085   
1       QUICK BITES          12680   
2     CASUAL DINING           1411   
3              None            204   
4       QUICK BITES          13453   
...             ...            ...   
4226  CASUAL DINING           9057   
4227           None           1247   
4228    QUICK BITES           8617   
4229    QUICK BITES           6485   
4230    QUICK BITES           2421   

                                           CUISINES  \
0             North Indian, Chinese, Mughlai, Kebab   
1      South Indian, Fast Food, Pizza, North Indian   
2           North Indian, Seafood, Biryani, Chinese   
3                                           Biryani   
4                              South Indian, Kerala   
...                                             ...   
4226                 North Indian, Mughlai, Chinese   
4227  Biryani, North Indian, Sandwich, Salad, Wraps   
4228                      Continental, North Indian   
4229                               Rolls, Beverages   
4230                                        Mughlai   

                                                   TIME         CITY  \
0                         12noon – 12midnight (Mon-Sun)        Noida   
1                               7am – 12:30AM (Mon-Sun)       Mumbai   
2                              11am – 11:30pm (Mon-Sun)       Mumbai   
3     9am – 10pm (Mon, Wed, Thu, Fri, Sat, Sun), 10:...    Faridabad   
4                                 11am – 10pm (Mon-Sun)        Kochi   
...                                                 ...          ...   
4226                        11:30am – 11:30pm (Mon-Sun)    New Delhi   
4227                               11am – 1am (Mon-Sun)    Bangalore   
4228                         9:30am – 10:30pm (Mon-Sun)    Faridabad   
4229  11am – 11:30pm (Mon, Tue, Wed, Thu, Sat, Sun),...        Kochi   
4230                                5pm – 1am (Mon-Sun)  Bandra West   

              LOCALITY RATING       VOTES  
0            Sector 18    4.3   564 votes  
1           Grant Road    4.2    61 votes  
2         Marine Lines    3.8   350 votes  
3                  NIT    3.8  1445 votes  
4               Kaloor    3.6    23 votes  
...                ...    ...         ...  
4226      Punjabi Bagh    3.9   287 votes  
4227        HSR Layout    4.3   469 votes  
4228         Sector 86    3.7    53 votes  
4229             Kochi      -         NaN  
4230  Perry Cross Road    3.7    63 votes  

[4231 rows x 8 columns]

In [5]:
train_data = pd.read_excel(r"C:\Users\ONYINYE EKEOCHA\Data_Train.xlsx")
train_data

TITLE  RESTAURANT_ID  \
0          CASUAL DINING           9438   
1      CASUAL DINING,BAR          13198   
2          CASUAL DINING          10915   
3            QUICK BITES           6346   
4         DESSERT PARLOR          15387   
...                  ...            ...   
12685        QUICK BITES          13228   
12686  CASUAL DINING,BAR           9686   
12687             LOUNGE          11133   
12688      CASUAL DINING           6134   
12689      CASUAL DINING           6430   

                                               CUISINES  \
0                           Malwani, Goan, North Indian   
1                        Asian, Modern Indian, Japanese   
2            North Indian, Chinese, Biryani, Hyderabadi   
3                                      Tibetan, Chinese   
4                                              Desserts   
...                                                 ...   
12685                       North Indian, Burger, Kebab   
12686                                 Goan, Continental   
12687          Finger Food, Continental, Asian, Chinese   
12688  North Indian, South Indian, Chinese, Street Food   
12689                             North Indian, Chinese   

                                                   TIME         CITY  \
0                11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)        Thane   
1                                  6pm – 11pm (Mon-Sun)      Chennai   
2                   11am – 3:30pm, 7pm – 11pm (Mon-Sun)      Chennai   
3                               11:30am – 1am (Mon-Sun)       Mumbai   
4                                  11am – 1am (Mon-Sun)       Mumbai   
...                                                 ...          ...   
12685  12noon – 12midnight (Mon, Tue, Wed, Thu, Sun)...    Hyderabad   
12686   12noon – 1am (Mon-Fri),11am – 5pm, 7pm – 1am...       Mumbai   
12687                        12noon – 12:30AM (Mon-Sun)  Navi Mumbai   
12688                           6am – 10:45pm (Mon-Sun)      Chennai   
12689                          12:30pm – 11pm (Mon-Sun)    Hyderabad   

                   LOCALITY RATING       VOTES  COST  
0            Dombivali East    3.6    49 votes  1200  
1                 Ramapuram    4.2    30 votes  1500  
2                Saligramam    3.8   221 votes   800  
3               Bandra West    4.1    24 votes   800  
4               Lower Parel    3.8   165 votes   300  
...                     ...    ...         ...   ...  
12685            Gachibowli    3.8   546 votes   500  
12686  Bandra Kurla Complex    4.3  1214 votes  1800  
12687                 Vashi    4.0   608 votes  1300  
12688           Maduravoyal    3.5    32 votes   400  
12689       Vanasthalipuram    3.4   677 votes   600  

[12690 rows x 9 columns]

In [6]:
test_data.dtypes

TITLE            object
RESTAURANT_ID     int64
CUISINES         object
TIME             object
CITY             object
LOCALITY         object
RATING           object
VOTES            object
dtype: object

In [7]:
train_data.dtypes

TITLE            object
RESTAURANT_ID     int64
CUISINES         object
TIME             object
CITY             object
LOCALITY         object
RATING           object
VOTES            object
COST              int64
dtype: object

In [8]:
test_data.isnull().sum()

TITLE              0
RESTAURANT_ID      0
CUISINES           0
TIME               0
CITY              35
LOCALITY          30
RATING             2
VOTES            402
dtype: int64

In [9]:
train_data.isnull().sum()

TITLE               0
RESTAURANT_ID       0
CUISINES            0
TIME                0
CITY              112
LOCALITY           98
RATING              2
VOTES            1204
COST                0
dtype: int64

In [11]:
# Separate features and target variable
X = train_data.drop('COST', axis=1)
y = train_data['COST']

In [12]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [13]:
# Numerical columns
numerical_features = X_train.select_dtypes(include=['int64', 'float64']).columns

# Categorical columns
categorical_features = X_train.select_dtypes(include=['object']).columns


In [14]:
# Imputation for numerical columns
num_imputer = SimpleImputer(strategy='mean')  
X_train[numerical_features] = num_imputer.fit_transform(X_train[numerical_features])
X_test[numerical_features] = num_imputer.transform(X_test[numerical_features])

# Imputation for categorical columns
cat_imputer = SimpleImputer(strategy='most_frequent')
X_train[categorical_features] = cat_imputer.fit_transform(X_train[categorical_features])
X_test[categorical_features] = cat_imputer.transform(X_test[categorical_features])

In [15]:
# Convert categorical features to numerical using one-hot encoding
X_train = pd.get_dummies(X_train, columns=categorical_features, drop_first=True)
X_test = pd.get_dummies(X_test, columns=categorical_features, drop_first=True)

# Align the test set to the training set (to handle missing columns after one-hot encoding)
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

In [17]:
#Scaling using standard scalarization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
# Create and train the Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [21]:
y_pred = model.predict(X_test)

In [22]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy * 100:.2f}%')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 19.03%
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
Classification Report:
              precision    recall  f1-score   support

          50       0.00      0.00      0.00         1
          60       0.00      0.00      0.00         1
          70       0.00      0.00      0.00         1
         100       0.40      0.10      0.16        41
         120       0.00      0.00      0.00         1
         150       0.26      0.19      0.22       108
         180       0.00      0.00      0.00         1
         200       0.24      0.22      0.23       209
         250       0.17      0.05      0.07       133
         300       0.23      0.47      0.31       337
         313       0.00      0.00      0.00         1
         350       0.04      0.01      0.02       106
         400       0.19      0.28      0.23       263
         450       0.17      0.01      0.03        72
         50

In [23]:
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

In [24]:
# Instantiate KNN Regression
knn = KNeighborsRegressor()

# Fit KNN Regression model
knn.fit(X_train, y_train)

# Make predictions with KNN Regression
pred_knn = knn.predict(X_test)

# Evaluate KNN Regression model
mse_knn = mean_squared_error(y_test, pred_knn)
print("KNN Regression Mean Squared Error:", mse_knn)

KNN Regression Mean Squared Error: 378421.9578723404


In [ ]:
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error


# Instantiate SVR
svr = SVR()

# Fit SVR model
svr.fit(X_train, y_train)

# Make predictions with SVR
pred_svr = svr.predict(X_test)

# Evaluate SVR model
mse_svr = mean_squared_error(y_test, pred_svr)
print("SVR Mean Squared Error:", mse_svr)